export type {
  Article,
  Bonus,
  Course,
  CourseModule,
  FAQItem,
  PortfolioItem,
  PresetProduct,
  Testimonial,
} from "./schemas";
export type { Login, Register, User } from "./schemas/auth";
export { LoginSchema, RegisterSchema, UserSchema } from "./schemas/auth";
export type { Block, BlockData, Content } from "./schemas/blocks";
export {
  AccordionBlock,
  BeforeAfterBlock,
  BlockSchema,
  CalloutBlock,
  CarouselBlock,
  CodeBlock,
  CollapseBlock,
  ColumnsBlock,
  ContentSchema,
  CTABlock,
  DividerBlock,
  GalleryBlock,
  HeadingBlock,
  ImageBlock,
  ListBlock,
  ParagraphBlock,
  PricingTableBlock,
  QuoteBlock,
  SpacerBlock,
  TableBlock,
  TabsBlock,
  TestimonialBlock,
  TimelineBlock,
  VideoBlock,
} from "./schemas/blocks";
export type { Media, MediaVariant } from "./schemas/media";

export { MediaSchema, MediaVariantSchema } from "./schemas/media";
export type {
  BonusGiftsConfig,
  BrandLogosConfig,
  CountdownOfferConfig,
  CurriculumHighlightsConfig,
  FAQAccordionConfig,
  FeaturedStudentsConfig,
  HeroBannerConfig,
  InstructorJourneyConfig,
  LessonAccordionConfig,
  PricingCardConfig,
  RichTextConfig,
  SalesStoryConfig,
  Section,
  SectionConfig,
  SectionType,
  TestimonialVideosConfig,
  TrustBadgesConfig,
} from "./schemas/sections";
export {
  BonusGiftsConfigSchema,
  BrandLogosConfigSchema,
  CountdownOfferConfigSchema,
  CurriculumHighlightsConfigSchema,
  ENTITY_SECTION_MAP,
  FAQAccordionConfigSchema,
  FeaturedStudentsConfigSchema,
  getDefaultConfig,
  HeroBannerConfigSchema,
  InstructorJourneyConfigSchema,
  LessonAccordionConfigSchema,
  MAX_SECTIONS,
  PricingCardConfigSchema,
  parseConfig,
  RichTextConfigSchema,
  SalesStoryConfigSchema,
  SECTION_CATALOG_GROUPS,
  SECTION_LABELS,
  SectionSchema,
  SectionTypeSchema,
  SINGLETON_SECTION_TYPES,
  TestimonialVideosConfigSchema,
  TrustBadgesConfigSchema,
  validateSectionConfig,
} from "./schemas/sections";
export {
  cx,
  formatDate,
  formatNumber,
  formatReadTime,
  formatVND,
} from "./utils";
